main/urls.py
from django.urls import path, re_path
from . import views

urlpatterns = [

    path('', views.index, name='index'),
    path('<int:display_board>/<str:message>',
         views.index, name='show_board'),
    path('<int:display_board>/', views.index, name='show_board'),

    path('create_new_board/', views.create_new_board,
         name='create_new_board'),

    re_path(r'^edit-board/(?P<board_id>.*)$', views.edit_board,
            name='edit_board'),

    re_path(r'^search/(?P<board_id>.*)$', views.search,
            name='search'),

    path('update_status/', views.update_status, name='update_status'),

]

taskflow/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("allauth.urls")),
    path('accounts/', include('allauth.socialaccount.urls')),
    path('', include('main.urls')),
    re_path('task/', include('task.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User


class Board(models.Model):
    '''
    Stores a kanban board and connects it to a single user account
    at :model:`auth.User`.
    '''
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name="board_to_user")
    title = models.CharField(max_length=255, blank=False, unique=False)
    description = models.TextField(blank=True)
    has_archived_tasks = models.BooleanField(default=False)
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["id"]

    def __str__(self):
        return self.title


class Column(models.Model):
    '''
    Stores a single Column within a Board and links it to one specific
    instance of :model:`main.Board`.
    '''
    title = models.CharField(blank=False, unique=False, max_length=255)
    colour = models.CharField(default='white', max_length=255)
    board = models.ForeignKey(Board, on_delete=models.CASCADE,
                              related_name="column_to_board")

    class Meta:
        ordering = ["id"]

    def __str__(self):
        return self.title


class Label(models.Model):
    '''
    Stores a Label within a Board, and links it to one specific
    Board instance at :model:`main.Board`.
    '''
    title = models.CharField(blank=False, unique=False, max_length=255)
    colour = models.CharField(default='light', max_length=255)
    board = models.ForeignKey(Board, on_delete=models.CASCADE,
                              related_name="label_to_board")

    def __str__(self):
        return f"*{self.title}* OF BOARD: {self.board}"

main/forms.py
from django import forms
from .models import Board


class CreateBoardForm(forms.ModelForm):
    '''
    Create Django Form for users to create new Boards
    '''
    class Meta:
        model = Board
        fields = ['title', 'description']

main/views.py
from django.shortcuts import render, HttpResponseRedirect, reverse
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import get_object_or_404  # noqa
import json
from .forms import CreateBoardForm
from .models import Board, Column, Label
from task.models import Task


@login_required
def index(request, display_board=None, message=None):
    '''
    Populates the main landing page with the currently selected instance
    of :model:`main.Board` and its accompanying information.
    **Context**
    ```all_boards```
        Queryset containing all current instances of :model:`main.Board`
        connected to the current user account.
    ```board```
        The primary key of the current instance of :model:`main.Board`.
    ```home```
        A boolean variable instructing the template to display navbar
        links relevant to the home page.
    ```home```
        A string variable that instructs the landing page template to
        display messages whenever tasks have been added or updated.
    **Template**
        template:`main/index.html`
    '''
    if request.user.board_to_user.all().count() == 0:
        create_initial_board(request)

    # Using Django `.only()` to minimize database queries.
    all_boards = Board.objects.only('title', 'id').filter(author=request.user)
    if display_board is not None:
        # Using Django `prefetch_related` to minimize database queries.
        current_board = Board.objects.prefetch_related(
            'column_to_board',
            'column_to_board__task_to_column',
            'column_to_board__task_to_column__label',
            'column_to_board__task_to_column__subtask_to_task',
            'label_to_board'
        ).filter(id=display_board).first()
    else:
        current_board = Board.objects.filter(author=request.user).first()

    return render(
        request,
        'main/index.html',
        {'all_boards': all_boards,
         'board': current_board,
         'home': True,
         'message': message}
        )


@login_required
def create_new_board(request):
    '''
    Allows creation of one new instance of `main.Board`. Each instance
    is connected to its respective Columns - :model:`main.Column` and
    Labels - :model:`main.Label`. This newly created instance is then
    returned to the main landing page to be displayed.
    **Context**
    ```new_board.id```
        The primary key of the newly created :model:`main.Board`
        to be displayed on the landing page.
    ```all_boards```
        Queryset containing all current instances of :model:`main.Board`
        connected to the current user account.
    ```board```
        The primary key of the current instance of :model:`main.Board`
    **Template**
        GET :template:`create_new_board.html`
        POST :template:`main/index.html`
    '''
    all_boards = Board.objects.filter(author=request.user)
    current_board = Board.objects.filter(author=request.user).first()

    if request.method == 'POST':

        user_input = CreateBoardForm(data=request.POST)
        if user_input.is_valid():
            new_board = user_input.save(commit=False)
            new_board.author = request.user
            new_board.save()

        # Add new Column Instance(s)
        add_cols = request.POST.getlist('column_title')
        for i in range(1, len(add_cols)+1):
            new_column = Column(
                title=add_cols[i-1],
                colour=request.POST.get(f'column_colour-{i}'),
                board=new_board
            )
            new_column.save()

        # Add new Label Instance(s)
        add_labels = request.POST.getlist('label_title')
        for i in range(1, len(add_labels)+1):
            new_label = Label(
                title=add_labels[i-1],
                colour=request.POST.get(f'label_colour-{i}'),
                board=new_board
            )
            new_label.save()

        return HttpResponseRedirect(reverse('show_board', args=[new_board.id]))

    return render(
        request,
        'main/create_new_board.html',
        {'all_boards': all_boards,
            'board': current_board}
        )


@login_required
def edit_board(request, board_id=None):
    '''
    Allows editing of one existing instance of `main.Board`. Each instance
    is connected to its respective Columns - :model:`main.Column` and
    Labels - :model:`main.Label`. This newly edited instance is then
    returned to the main landing page to be displayed.
    **Context**
    ```board_id```
        The primary key of the newly edited :model:`main.Board`
        to be displayed on the landing page.
    ```all_boards```
        Queryset containing all current instances of :model:`main.Board`
        connected to the current user account.
    ```board```
        The primary key of the current instance of :model:`main.Board`
    **Template**
        GET :template:`main/edit_board.html`
        POST :template:`main/index.html`
    '''
    all_boards = Board.objects.filter(author=request.user)
    current_board = Board.objects.filter(id=board_id).first()

    if request.method == 'POST':
        # Update Board Title & Description
        current_board.title = request.POST.get('title')
        current_board.description = request.POST.get('description')
        current_board.save()

        # Update Column Titles & Colours
        new_column_names = request.POST.getlist('column_title')
        update_columns = request.POST.getlist('column-id')

        for i in range(len(new_column_names)):
            # Update Existing Column (Current column.id = present)
            if i < len(update_columns):

                current_column = Column.objects.filter(
                    id=update_columns[i]).first()
                current_column.title = new_column_names[i]
                current_column.colour = request.POST.get(
                    f'column_colour-{i+1}')
                current_column.save()
            # Create New Column (Since no current column.id present)
            else:
                new_column = Column(
                    title=new_column_names[i],
                    colour=request.POST.get(f'column_colour-{i+1}'),
                    board=current_board
                )
                new_column.save()

        # Update Label Titles & Colours
        new_label_names = request.POST.getlist('label_title')
        update_labels = request.POST.getlist('label-id')

        for i in range(len(new_label_names)):
            # Update Existing label (Current label.id = present)
            if i < len(update_labels):

                current_label = Label.objects.filter(
                    id=update_labels[i]).first()
                current_label.title = new_label_names[i]
                current_label.colour = request.POST.get(
                    f'label_colour-{i+1}')
                current_label.save()
            # Create New label (Since no current label.id present)
            else:
                new_label = Label(
                    title=new_label_names[i],
                    colour=request.POST.get(f'label_colour-{i+1}'),
                    board=current_board
                )
                new_label.save()

        return HttpResponseRedirect(reverse(
            'show_board', args=[board_id, 'board_updated']))

    return render(
        request,
        'main/edit_board.html',
        {'all_boards': all_boards,
         'board': current_board}
        )


@login_required
def search(request, board_id):
    '''
    Allows a user to search through all instances of :model:`task.Task`
    on the current instance of :modal:`main.Board`. The view returns
    a queryset of search results to be displayed on a search results page.
    Task name and description fields are searched.
    **Context**
    ```all_boards```
        Queryset containing all current instances of :model:`main.Board`
        connected to the current user account.
    ```board```
        The primary key of the current instance of :model:`main.Board`.
    ```search_results```
        A queryset of found instances of :model:`task.Task`.
    ```user_search```
        A string variable containing the phrase searched by the user.
    ```count```
        An integer of the number of items found.
    ```home```
        A boolean variable confirming to the template to display navbar
        links relevant to the home page.
    **Template**
        GET :template:`main/edit_board.html`
        POST :template:`main/index.html`
    '''
    all_boards = Board.objects.filter(author=request.user)
    current_board = Board.objects.filter(id=board_id).first()

    current_board_tasks = Task.objects.filter(
        column__in=current_board.column_to_board.all())

    if request.method == 'POST':
        user_search = request.POST.get('user_search')
        search_results = current_board_tasks.filter(
            title__icontains=user_search) | current_board_tasks.filter(
            description__icontains=user_search)

        count = len(search_results)

    return render(
        request,
        'main/search_results.html',
        {'all_boards': all_boards,
         'board': current_board,
         'search_results': search_results,
         'user_search': user_search,
         'count': count,
         'home': True}
        )


@login_required
def create_initial_board(request):
    '''
    Relevant for newly created instances of :model:`auth.User`.
    Newly registered users do not start with empty Boards, instead, this
    view generates initial models for the landing page. It creates the
    following instances:
    :model:`main.Board` x 1
    :model:`main.Column` x 3
    :model:`main.Label` x 1
    :model:`task.Task` x 1
    These instances are then returned to the main landing page to be
    displayed there.
    **Context**
    ```first_board.id```
        The primary key of the newly created instance of :model:`main.Board`
    **Template**

main/templates/main/create_edit_board.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<script src="{% static 'assets/js/create-board.js' %}" defer="defer"></script>
<div class="p-3">
    <h1 class="mt-3">Create a Board</h1>
    <form id="add-border-form" method="post" style="margin-top: 2em; margin-bottom: 2em;">
        <div id="div_id_title" class="mb-3">
            <label for="id_title" class="form-label requiredField">
                Title
                <span class="asteriskField">*</span>
            </label>
            <input type="text" name="title" maxlength="200" class="textinput form-control" required id="id_title">
        </div>
        <div id="div_id_description" class="mb-3">
            <label for="id_description" class="form-label">
                Description
            </label>
            <textarea name="description" cols="40" rows="5" class="textarea form-control"
                id="id_description"></textarea>
        </div>

        <!-- Columns -->

        <div class="border-container">
            <div class="mb-3">
                <label for="column_title" class="form-label requiredField">
                    Column 1 Title
                    <span class="asteriskField">*</span>
                </label>
                <input type="text" name="column_title" maxlength="200" class="textinput form-control" required
                    id="column_title_1">
            </div>
            <span class="mb-2">Choose a colour for Column 1:</span>
            <div class="mb-3">
                <input type="radio" class="btn-check" name="column_colour-1" value="0" id="black-1" checked>
                <label class="btn btn-outline-secondary" for="black-1">Black</label>

                <input type="radio" class="btn-check" name="column_colour-1" value="1" id="blue-1">
                <label class="btn btn-outline-primary" for="blue-1">Blue</label>

                <input type="radio" class="btn-check" name="column_colour-1" value="2" id="green-1">
                <label class="btn btn-outline-success" for="green-1">Green</label>
            </div>
        </div>
        <button type="button" id="create-new-column" class="btn btn-lg btn-primary mt-3 mb-5">Add
            Column</button>
        <button type="button" id="remove-new-column" class="btn btn-lg btn-danger mt-3 mb-5"
            style="display: none;">Remove Column</button><br>

        <!-- Labels -->

        <div class="border-container">
            <div class="mb-3">
                <label for="label_title" class="form-label requiredField">
                    Label 1 Title
                    <span class="asteriskField">*</span>
                </label>
                <input type="text" name="label_title" maxlength="200" class="textinput form-control" required
                    id="label_title_1">
            </div>
            <span class="mb-2">Choose a colour for Label 1:</span>
            <div class="mb-3">
                <input type="radio" class="btn-check" name="label_colour-1" value="0" id="label-black-1" checked>
                <label class="btn btn-outline-secondary" for="label-black-1">Black</label>

                <input type="radio" class="btn-check" name="label_colour-1" value="1" id="label-blue-1">
                <label class="btn btn-outline-primary" for="label-blue-1">Blue</label>

                <input type="radio" class="btn-check" name="label_colour-1" value="2" id="label-green-1">
                <label class="btn btn-outline-success" for="label-green-1">Green</label>
            </div>
        </div>
        <button type="button" id="create-new-label" class="btn btn-lg btn-primary mt-3 mb-5">Add Label</button>
        <button type="button" id="remove-new-label" class="btn btn-lg btn-danger mt-3 mb-5"
            style="display: none;">Remove Label</button><br>



        {% csrf_token %}
        <button type="submit" class="btn btn-lg btn-success mt-3 me-2">Add Board</button>
    </form>
    <script src=""></script>
</div>

{% endblock %}

main/templates/main/create_new_board.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<!-- Page Specific Javascript -->
<script src="{% static 'assets/js/create-board.js' %}" defer></script>

<div class="container col-md-6 mt-md-3 mb-5 pb-3">
    <h3 class="mt-3 text-center">Create A New Kanban Board</h3>
    <form id="add-border-form" method="post" style="margin-top: 2em; margin-bottom: 2em;">
        
        <!-- New Board Title -->
        <div id="div_id_title" class="mb-3">
            <label for="id_title" class="form-label requiredField">
                Title
                <span class="asteriskField">*</span>
            </label>
            <input type="text" name="title" maxlength="200" class="textinput form-control" pattern="[^\s].*" required id="id_title" placeholder="What project will you be tracking?">
        </div>

        <!-- New Board Description -->
        <div id="div_id_description" class="mb-3">
            <label for="id_description" class="form-label">
                Description
            </label>
            <textarea name="description" cols="40" rows="3" class="textarea form-control"
                id="id_description" placeholder="Provide some more project detail..."></textarea>
        </div>

        <!-- New Board Columns | Two initial columns available -->
        <div class="mt-4">
            <h6>Create New Columns for your board</h6>
            <p>Note: <em>Tasks in the <strong>final</strong> column are always interpreted as completed.</em></p>
        </div>
        <div class="border-container">

            <!-- Column Title -->
            <div class="mb-3">
                <label for="column_title_1" class="form-label requiredField">
                    Column 1 Title
                    <span class="asteriskField">*</span>
                </label>
                <input type="text" name="column_title" maxlength="200" pattern="[^\s].*" class="textinput form-control col-titles" required
                    id="column_title_1" placeholder="e.g. 'Todo'">
            </div>

            <!-- Column Colour -->
            <span class="mb-2">Choose a colour for Column 1:</span>
            <div class="mb-3">
                <input type="radio" class="btn-check" name="column_colour-1" value="white" id="white-1" checked>
                <label class="btn btn-light colour-selector" for="white-1">White</label>

                <input type="radio" class="btn-check" name="column_colour-1" value="red" id="red-1">
                <label class="btn btn-outline-danger colour-selector" for="red-1">Red</label>

                <input type="radio" class="btn-check" name="column_colour-1" value="green" id="green-1">
                <label class="btn btn-outline-success colour-selector" for="green-1">Green</label>
                
                <input type="radio" class="btn-check" name="column_colour-1" value="blue" id="blue-1">
                <label class="btn btn-outline-primary colour-selector" for="blue-1">Blue</label>

                <input type="radio" class="btn-check" name="column_colour-1" value="yellow" id="yellow-1">
                <label class="btn btn-outline-warning colour-selector" for="yellow-1">Yellow</label>
            </div>
            <hr>
            <div class="mb-3">
                <label for="column_title_2" class="form-label requiredField">
                    Column 2 Title
                    <span class="asteriskField">*</span>
                </label>
                <input type="text" name="column_title" maxlength="200" pattern="[^\s].*" class="textinput form-control col-titles" required
                    id="column_title_2" placeholder="e.g. 'Doing'">
            </div>
            <span class="mb-2">Choose a colour for Column 2:</span>
            <div class="mb-3">
                <input type="radio" class="btn-check" name="column_colour-2" value="white" id="white-2">
                <label class="btn btn-light colour-selector" for="white-2">White</label>

                <input type="radio" class="btn-check" name="column_colour-2" value="red" id="red-2">
                <label class="btn btn-outline-danger colour-selector" for="red-2">Red</label>

                <input type="radio" class="btn-check" name="column_colour-2" value="green" id="green-2" checked>
                <label class="btn btn-outline-success colour-selector" for="green-2">Green</label>
                
                <input type="radio" class="btn-check" name="column_colour-2" value="blue" id="blue-2">
                <label class="btn btn-outline-primary colour-selector" for="blue-2">Blue</label>

                <input type="radio" class="btn-check" name="column_colour-2" value="yellow" id="yellow-2">
                <label class="btn btn-outline-warning colour-selector" for="yellow-2">Yellow</label>
            </div>
        </div>

        <!-- Add Extra Column (populated by Javascript) -->
        <button type="button" id="create-new-column" class="btn btn-primary mt-3 mb-5">Add
            Column</button>
        <button type="button" id="remove-new-column" class="btn btn-danger mt-3 mb-5"
            style="display: none;">Remove Column</button><br>

        <!-- Column Labels to use with board tasks-->
        <div class="border-container">
            <div class="mb-3">
                <label for="label_title_1" class="form-label requiredField">
                    Label 1 Title
                    <span class="asteriskField">*</span>
                </label>
                <input type="text" name="label_title" maxlength="200" class="textinput form-control" required
                    id="label_title_1" placeholder="e.g. 'urgent'">
            </div>
            <span class="mb-2">Choose a colour for Label 1:</span>
            <div class="mb-3">
                <input type="radio" class="btn-check" name="label_colour-1" value="light" id="label-white-1">
                <label class="btn btn btn-light colour-selector" for="label-white-1">White</label>

                <input type="radio" class="btn-check" name="label_colour-1" value="danger" id="label-red-1" checked>
                <label class="btn btn-outline-danger colour-selector" for="label-red-1">Red</label>

                <input type="radio" class="btn-check" name="label_colour-1" value="success" id="label-green-1">
                <label class="btn btn-outline-success colour-selector" for="label-green-1">Green</label>
                
                <input type="radio" class="btn-check" name="label_colour-1" value="primary" id="label-blue-1">
                <label class="btn btn-outline-primary colour-selector" for="label-blue-1">Blue</label>

                <input type="radio" class="btn-check" name="label_colour-1" value="warning" id="label-yellow-1">
                <label class="btn btn-outline-warning colour-selector" for="label-yellow-1">Yellow</label>
            </div>
        </div>

        <!-- Add Extra Labels (populated by Javascript) -->
        <button type="button" id="create-new-label" class="btn btn-primary mt-3 mb-5 small">Add Label</button>
        <button type="button" id="remove-new-label" class="btn btn-danger mt-3 mb-5 small"
            style="display: none;">Remove Label</button><br>

        {% csrf_token %}
        <button type="submit" id="submit-new-board" class="btn btn-lg btn-success mt-3 me-2">Add Board</button>
    </form>
</div>

{% endblock %}